registry:
  image: 10.32.105.134:5000/registry:2
  restart: always
  ports:
    - 5000:5000
    - 5001:5001
  environment:
#    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/emc.crt
#    REGISTRY_HTTP_TLS_KEY: /certs/emc.key
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
  volumes:
    - ./images:/var/lib/registry
  # - ./emc_cer:/certs

registryui:
  image: 10.32.105.134:5000/docker-registry-ui
  restart: always
  ports:
    - 8099:8080
  environment:
    REG1: "http://10.32.105.153:5000/v1/"
  volumes:
    - ./registry-ui_data:/var/lib/h2
